### ISSUE TITLE
Well of Suffering active, but not damaging mobs

### ISSUE THREAD

**Issue by Nonsanity** [WayofTime/BloodMagic#483] opened 2015-10-28 03:38 UTC
On our server, the Well of Suffering will activate if properly set up and given the correct amount of LP. However it does not damage any mobs. The confg file is default, so this is not due to any disabling of those mobs. Instead of taking damage, zombies within range get a twitchy head.

A video of this bug in action can be seen here: https://www.youtube.com/watch?v=Y-3vq3aZULg

Previously, and with the same selection of mods with the same versions, the WoS worked as it should. At one point it just stopped working and no amount of restarts or chicken-waving has gotten it to work again. This is the same for everyone that has tried, including an Op that hadn't yet touched Blood magic prior to testing this, so it is unlikely to be corrupted user data. I was unable to find any data files that seemed obviously linked to Blood Magic, so I don't know if this is due to file corruption.

Forge: forge-1.7.10-10.13.4.1492-1.7.10-universal
Mod list: https://gist.github.com/Nonsanity/026c78ba3663c7fcb3c0

**Comment by TehNut** [comment] 2015-10-28 04:32
1. You need to do voice acting.
2. Is the server running KCauldron?

Is this the issue that was brought up in the forum thread? If so, I remember ServerTools (@matthewprenger) was brought up. Is the issue resolved if that is removed?

**Comment by Nonsanity** [comment] 2015-10-28 05:47
1. That would be fun, but after doing the one audiobook on my channel, I don't think I have the talent for it.
2. No KCauldron or Cauldron or anything similar—strait-up Forge only.

I tried removing all the server-side mods down at the bottom of the list—including ServerTools—but none of them made a difference to the problem.

**Comment by TehNut** [comment] 2015-10-28 05:58
`/gamerule doDaylightCycle` is true, right?

**Comment by WolfAmaril** [comment] 2015-10-28 06:29
Have you tried it with a T4 or above altar?
I've noticed that the WoS won't place blood into an altar that's too low tier.

**Comment by TehNut** [comment] 2015-10-28 06:32
As far as I can tell, there are no direct checks to the tier of Altar.

**Comment by Nonsanity** [comment] 2015-10-28 06:41
I think we've tried up to a tier 5.

As far as I know, no gamerules have been changed. I'll check that one tomorrow though, in case something else has modified it unexpectedly. We do have day and night cycles—and the occasional blood moon.

**Comment by Nonsanity** [comment] 2015-10-28 06:43
Other rituals we have tried do work, by the way. And the Drill of the Dead (Sanguimancy?) works as well. So far, only the Well of Suffering has stopped working.

**Comment by Blue64** [comment] 2015-12-25 06:07
I just started getting this error too, although I've yet to see any zombies. I may need an update too. 
```
MC 1.7.10
Forge 10.13.4.1614 for 1.7.10
Blood Magic 1.3.3-17 for 1.7.10
And presently 117 other mod files are also active
```
Built in creative mode, along with a Tier 4 Altar placed directly above it (also verified that it wasn't requiring some lightning strike by building it separate with zero altar), it eats the 50k LP, says that energy surges into the Master Ritual Stone, WAILA says I'm the owner, says that it's the correct ritual, and that's where it stops. The EnderIO mobs are untouched, along with spiders, and, ooh, even a regular zombie (no funky graphics), skeleton is unhurt too. It's running (twice now) and yet, no damage to any creatures. My main blocks used are from
```
Extra Utilities
  * Dark Ethereal Glass
  * Cursed Earth
  * Ineffable Glass (pillars for Altar's Glowstones & Large Bloodstone Bricks)
Thaumcraft
  * Paving Stones of Warding (not needed)
Blood Magic
  * Blood Altar Tier 4
    * Rune of Superior Capacity (outter layer)
    * Rune of Self-Sacrifice (all the others)
  * Blood Altar Tier 1
  * all the stuff for the Ritual (Well of Suffering)
  * Ritual Diviner (Dawn and Dusk Rune capable)
  * Awakened Activation Crystal (1st few tries)
  * Creative Activation Crystal (still didn't work)
  * Seer & Sight Sigils
  * Sacrificial Knife (to fill the Altar with my Creative Mode LP lol)
MineCraft
  * Bricks
  * Brick Slabs
  * Brick Stairs
```
As it provided zero information in the logs, and didn't crash, idk what else to tell you.

I'm in a superflat world that's nothing but 1 layer of bedrock, I built anything actually existing in this superflat world beyond the bedrock lol

**Comment by Blue64** [comment] 2015-12-26 03:42
Forgot to mention, I also tried it with an upkeep cost of 2, but 0 upkeep was(/is) being drained.

**Comment by Blue64** [comment] 2015-12-29 13:38
Verified direct Line of Sight to the Ritual (placed around ```y10```, Cursed Earth placed at ```y1```), still no damage. I have since moved on to testing other stuff while waiting to get feedback from here.

**Comment by Blue64** [comment] 2016-01-01 18:23
@TehNut did you ever figure out the cause of this in 1.7.10?

**Comment by TehNut** [comment] 2016-01-01 18:57
No, I didn't bother looking at it any further since 1.7.10 is EOL.

**Comment by Blue64** [comment] 2016-01-01 19:14
```*facepalm*``` I was really looking forward to this ritual too. Honestly, this ritual was actually the initial reason I grabbed this mod, I got tired of mass killing the overabundance of squid spawns using SuperMasiveTech to drag em out of the water, and also hoped to use this to kill those pesky bats too lol go figure, I can light up the catacombs under my base down to bedrock, but it takes me 3 min to kill 1 bat lol

**Comment by Blue64** [comment] 2016-01-01 19:25
@ljfa-ag any ideas from your point of view? I figured you might have some insight since you know your way around the rituals a bit.

**Comment by ljfa-ag** [comment] 2016-01-01 19:51
Not sure either. I know that when doDaylightCycle is turned off, world.getWorldTime() will stop increasing. In this case other rituals will not work either though (and in this case it can be fixed by replacing getWorldTime() by getTotalWorldTime()).

I guess we won't really have insight without debugging it.

**Comment by Blue64** [comment] 2016-01-01 20:00
My other rituals worked just fine (had the Zypher working, and Attraction working as well), could it be something before that? I think the error may perhaps be somewhere around the call for the upkeep of the ritual, as it has zero upkeep even when given an upkeep.

**Comment by Blue64** [comment] 2016-01-10 00:35
Did some more testing yesterday in a new world, and now it works, although I notice the LP Drain is only per Damaging Tick, not per Tick. I also notice the Well of Suffering will not cause Compound Damage if you build a second one directly above the previous one (I had 1 below a Tier 4 Altar & 1 Above the same Altar, but the Witches still died at the same speed...**_VERY**_ _slowly_)

I have no idea why it was broken before, but now works. I did notice a bug though. I shall post them in a separate issue, at least for the sake of having the issue up so nobody else will complain about it.

I suspect the Ritual broke due to at one point turning off the DoDaylightCycle, but I re-enabled it, and that should have fixed it.

I also notice the ritual has a rather short reach compared to the size of the area needed to build it (only around 6 blocks away from the outer edges of the ritual if I'm not mistaken), thus limiting the usefulness of this ritual, and I see no config section to increase this radius. What would need to be done in order to add that config option to 1.7.10 exactly? (I have very little hope of the currently active Authors actually implementing AoE Config for 1.7.10, so I'd likely do it myself eventually)

**Comment by Alexismachina** [comment] 2016-01-13 01:07
@Nonsanity Even tough of doing a youtube channel ? lol

**Comment by TehNut** [comment] 2016-01-17 20:11
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.

**Closed by TehNut** 2016-01-17 20:11 UTC
Labels: bug
