### ISSUE TITLE
Mending not working...

### ISSUE THREAD

**Issue by Stephenator0316** [WayofTime/BloodMagic#1027] opened 2017-01-16 18:26 UTC
#### Issue Description:

Mending isn't working on my Sentient Sword when I collect XP. It has Unbreaking 3, Sharpness 5, Mending, and looting 3

#### What happens:

Nothing, that's the issue

#### What you expected to happen:

My sword to repair itself

#### Steps to reproduce:

1. Put enchants on sword
2. Gather XP

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.9.4-2.1.0-69
- Minecraft: 1.10.2
- Forge: 12.18.3.2202

**Comment by TehNut** [comment] 2017-02-05 06:59
Mending is working perfectly fine for me.

**Comment by TehNut** [comment] 2017-02-13 21:51
Are you sure you were using the enchantment properly? I'm going to close this issue if it doesn't get any activity since I can't reproduce it.

**Closed as completed** 2017-02-20 22:20 UTC
Labels: cannot reproduce
