### ISSUE TITLE
Sigil of suppression still has one minor bug :(

### ISSUE THREAD

**Issue by afghan2007** [WayofTime/BloodMagic#814] opened 2016-06-24 00:25 UTC
#### What happens:

Masterful work on the suppression sigil but, although is suppresses lava/water/life essence sources only lava and water sources return after the effect end.  Life essence source are permanently removed.  My fields are nurtured with life essence instead of water and I ran passed them with my sigil of suppression activated...lol started to notice the issue when I returned to a dried up crop.  Sigil turned off. All life essence sources effected were gone.
#### What you expected to happen:

 I'm pretty sure the sigil of suppression wasn't meant to permanently remove any source.  I am starting to wish I understood modding more cause it sucks showing all these problems and not having many solutions to offer up with them.
#### Steps to reproduce:
1. Use sigil of suppression on life essence and see if it come back after effect is turned off.
2. 
3. 
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: BloodMagic-1.9.4-2.0.2-45
- Minecraft: 1.9.4
- Forge: forge-1.9.4-12.17.0.1910-1.9.4-installer-win.exe

**Comment by TehNut** [comment] 2016-06-24 00:35
Unable to reproduce.

https://gfycat.com/AgitatedRegalGibbon

Though I did find an issue where it just places source blocks instead of flowing (For Life Essence).

**Comment by TehNut** [comment] 2016-06-24 00:47
Okay the issue I found is because `BlockFluidBase` doesn't override `getStateFromMeta(int)`. This is actually a Forge bug and will exist in any modded fluids.

**Comment by afghan2007** [comment] 2016-06-24 00:52
Thanks ill look for a newer version of forge.

**Comment by TehNut** [comment] 2016-06-24 00:54
It is not fixed in Forge.

**Comment by TehNut** [comment] 2016-06-25 22:49
Still requires a fix on Forge's end for all other mods to work correctly.

**Closed as completed** 2016-06-27 15:25 UTC
Labels: bug, Fixed in Dev, 1.9
