### ISSUE TITLE
[1.8.9] Ticking entity crash on world restart while the altar is crafting

### ISSUE THREAD

**Issue by DrasticDemise** [WayofTime/BloodMagic#658] opened 2016-03-07 06:20 UTC
There was a similar crash report, but it was not in reference to the crafting altar, apologies if this is a repeat.
#### Issue Description:

If an altar is mid-crafting, in this instance blank slates, and the server restarts, the altar will throw a ticking block entity upon load into the world. Server crash report found here: http://pastebin.com/TN3HiwAs
#### Steps to reproduce:
1. Place objects in the blood altar for crafting
2. While the altar is crafting, restart the server
3. Load the altar again.
   ...

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 2.0.0-19
- Minecraft: 1.8.9
- Forge: 1764

**Comment by TehNut** [comment] 2016-03-07 06:55
Dupe of #651

**Closed as completed by TehNut** 2016-03-07 06:55 UTC
Labels: duplicate, 1.8
