### ISSUE TITLE
[1.16.5] Client-crash after putting living armor

### ISSUE THREAD

**Issue by Tristan-LeBras** [WayofTime/BloodMagic#1853] opened 2021-10-06 22:36 UTC
#### Issue Description:
Client-crash after putting the 'living armor' in Valhesia 3.4.4 on a server (linked the crash report to Val3 team and they asked me to put it here).
Cannot relog 'internal server error' .

#### What happens:
I just crafted the full set of 'living armor' and the moment I put it on I crashed.
After that I'm not able to connect to the server 'internal server error' but others can and they can play normally.

#### Steps to reproduce:
Don't know if Valhesia 3 has an impact here (didn't test the mod alone)
1.  Put the living armor
2.  Enjoy the crash
3. 
...

____
#### Affected Versions (Do *not* use "latest"):
Valhesia 3.4.4 launched via Curseforge
- BloodMagic: BloodMagic-1.16.4-3.1.5-25
- Minecraft: 1.16.5
- Forge: 36.2.8

Link to log + crash report :
https://gist.github.com/Tristan-LeBras/188c165e08d8e117d43edce40c22d1a3

**Comment by the-first-ideal** [comment] 2021-10-25 02:46
Tried the downgrade, that didn't work, so as admin of the server I spammed /clear [playerName] bloodmagic:livingplate over and over as my player joined the server. It finally caught him, so now he can play. 
It does seem like though that there is a potential fix from user VT-14, just needs to be implemented.

**Comment by Takeuout** [comment] 2021-11-06 00:17
Putting on the full set of living armor completely breaks the game... had to roll back the server.
i have seen posts about this going back as far as 2017 does this actually ever plan on getting fixed?

enigmatica 6 
Minecraft Version: 1.16.5
Modpack Version: 0.5.20

[05.11 16:54:22] [Server] Caused byjava.lang.NullPointerException: Cannot invoke "wayoftime.bloodmagic.core.living.LivingStats.getLevel(net.minecraft.util.ResourceLocation)" because the return value of "wayoftime.bloodmagic.core.living.LivingStats.fromPlayer(net.minecraft.entity.player.PlayerEntity)" is null
[05.11 16:54:22] [Server] 	at wayoftime.bloodmagic.common.item.ItemLivingArmor.hasElytraUpgrade(ItemLivingArmor.java:224) ~[bloodmagic:1.16.4-3.1.5-{re:classloading,pl:runtimedistcleaner:A}
[05.11 16:54:22] [Server] 	at wayoftime.bloodmagic.common.item.ItemLivingArmor.canElytraFly(ItemLivingArmor.java:210) ~[bloodmagic:1.16.4-3.1.5-{re:classloading,pl:runtimedistcleaner:A}

**Comment by wrincewind** [comment] 2021-11-06 00:42
the bug isn't from 2017 - it was introduced in version 19(?) or so, with the Elytra upgrade, and only occurs on modpacks with the Caelus API, or other APIs that interact with Elytra flight. A fix has been PRd and will be included in the next version.

**Comment by Infinoid** [comment] 2021-11-08 20:23
> enigmatica 6 Minecraft Version: 1.16.5 Modpack Version: 0.5.20

I got the same crash in the same modpack.  It crashes the first time I put on the full set of living armor, and it crashes again after restarting the game  and re-entering the (single-player) world.

I tried a custom build of the mod with #1856 applied, and confirmed that it fixes the crash for me.

**Closed as completed** 2021-11-15 17:10 UTC
Labels: bug, 1.16

**Comment by Darkmega18** [comment] 2021-11-24 17:26
Soooo, when can we expect this one to drop in an update? it seems like quite a big one for those budding blood magic enthusiasts and probably worth the triage hotfix update... and it happens in my own pack also. A friend got hit by it just the other night. Glad it's know and has been slapped out though.

**Comment by TehNut** [comment] 2021-11-24 19:49
When Way has time to do a release. We have lives outside of this hobby.

**Comment by Darkmega18** [comment] 2021-11-25 05:00
shoulda expected that kinda response honestly, and I didn't mean to insinuate that you don't have lives, but I guess big mod takes more time to build a release than others and theres probably devvy-tester things still enabled in dev that would slow that down... :V

**Comment by M-W-K** [comment] 2021-12-06 22:31
I'm getting crashes as well, but with version 3.1.6 - 26 that was supposed to have fixed this. Exact same behavior, though it might've been caused from conflict with other mods I'm running.
Have a server log w/ the issue occurring:
[latest.log.zip](https://github.com/WayofTime/BloodMagic/files/7663963/latest.log.zip)
