### ISSUE TITLE
Problems with demon invasion

### ISSUE THREAD

**Issue by tyler2k15** [WayofTime/BloodMagic#498] opened 2015-11-15 17:29 UTC
Hello,

 I have a player on my server that tried a demon invasion but it messed up. Is there a way to reset it so it can be redone or a configure to allow more than one per world?

Thanks!

**Comment by TehNut** [comment] 2015-11-15 17:39
What do you mean "it messed up"? Also, as far as I can tell, nothing stops you from having more than one per world.

**Comment by tyler2k15** [comment] 2015-11-15 18:19
I don't know the exact details of what happened, I am just relaying information at this point. I was also informed by one of our senior staff members that it could only be done once per world. If this isn't the case, then I can relay the message and see about having it redone.

**Comment by chrisbecke** [comment] 2015-11-21 13:44
One of (the most popular when I looked) the Blood Magic Demon Invasion how-to videos on YouTube has the claim that there can only be one per server. There is perhaps a restriction such that they need to be 1000m from each other?

**Comment by TehNut** [comment] 2015-11-21 18:06
<TehNut|Sleep> WayofTime: Is there a limit on how many invasions can be active per world?
    <-> You are now known as TehNut
    <WayofTime> No
    <WayofTime> There's a limit of 100 demons per invasion, however - there was an oops earlier where that 100 limit applied to all invasions, but that was fixed months ago

**Comment by Zaflis** [comment] 2015-12-13 15:16
> <WayofTime> There's a limit of 100 demons per invasion, however

Ha, no wonder we stopped seeing any from spawning. We waited for 3 realtime days while server online and area chunkloaded for 24 hours a day. After killing what bunch spawned at start, none did afterwards. It was a flat dimension and it became a huge empty metropolis.

**Comment by Blue64** [comment] 2015-12-13 18:50
is that upper limit configurable?

**Comment by Zaflis** [comment] 2015-12-13 19:05
Seems to be this

    I:demonHoardLimit=100

But i don't know if it's intended to be *simultaneously* active demons, not summon count for entire lifetime of demon village.

**Comment by Blue64** [comment] 2015-12-13 19:32
@Zaflis that sounds like a ```Request``` to me!
```
Separate config for:
  I: maxSimultaneousDemonsViaRitual=[int]
  (thus avoiding nerfing custom spawning via other methods), 
  
  I: maxHordeLimit=[int]
  which obviously suggests:
  I: minHordeLimit=[int]
```
and please don't forget to use the ```[int]``` that caps out over 2 billion, otherwise, well:
how do you generate a ```maxHordeLimit=-1379``` again?

**Comment by WayofTime** [comment] 2015-12-13 19:35
These types of improvements will be explored and made in the 1.8.8 update of the mod. We are currently writing the update, but it will take some time. Who knows, the invasion may be totally different when we port it over!

But yeah, I think that the limit is the max simultaneous demons per invasion. But because your invasion got so... large, the demons are few and far between!

**Comment by Blue64** [comment] 2015-12-13 20:21
Sounds awesome! ```^_^``` I'm looking forward to this... Although, I still have zero clue as to how I'm supposed to get the ```Orb``` to fill while it's resting in the ```Altar``` (even in Survival it doesn't work, probably a version issue, but ya never know).
```
Forge10.13.4.1558-1.7.10
BloodMagic-1.7.10-1.3.0b-3
```
[Updating now](http://minecraft.curseforge.com/projects/blood-magic/files/2264826)...
ERROR: Did not see this issue mentioned in changelog!

I crafted the ```Altar```, I then crafted the ```Tier 3 Orb``` (```Gold Block```) in the ```Altar```, took it out, ```Bound``` it to myself, placed it back in, filled the ```Altar``` with about ```50 Buckets``` (```50,000 mB```) of ```Blood``` via the ```Sacrifical Blade``` (Villagers and Pigs gave their lives to test this... mostly Pigs), but my ```Sigils``` (```Divination & Seer both```) were registering no ```Blood``` draining from the ```Altar```, and my ```Network``` wasn't filling at all, despite being empty (```LP: 0```).

I also noticed that the ```Altar``` doesn't recognize the swapped out ```Runes``` & it's ```Tier``` until something else updates the ```Altar``` it's self (such as adding/removing ```Blood```). While this aids in reducing Lagg, it isn't updated when checked via ```Sigils```, so if your ```Altar``` is missing a Block somewhere, you'll never know until you start to use it, and the same goes for if you have it correctly built. The ```Sigils``` will even continue stating the incorrect ```Tier```. Perhaps you could at the very least include the ```Forced Block Update``` on the ```Altar``` when it is checked via the ```Seer/Divination Sigil``` (and whatever ```Sigil``` holds the other ```Sigils``` within it while it contains the ```Seer/Divination Sigil```)

**Comment by TehNut** [comment] 2015-12-14 02:15
> it isn't updated when checked via Sigils

**Comment by Blue64** [comment] 2015-12-14 02:38
Fixed in 1.8.
so I can't expect to see this in 1.7.10? also, I don't see any versions for 1.8 on that CurseForge post. is it elsewhere?

**Comment by TehNut** [comment] 2015-12-14 02:41
>so I can't expect to see this in 1.7.10?

**Comment by Blue64** [comment] 2015-12-14 03:28
so... it's fixed... but not available? xD doesn't that mean it's only "in progress"?

**Comment by TehNut** [comment] 2015-12-14 05:30
No, because in code, it is fixed. Not being released does not mean it is not fixed. Do not argue semantics with me.

**Comment by TehNut** [comment] 2016-01-17 20:10
Because the 1.7.10 build of BM is no longer being worked on, we are clearing out non-critical issues for that version. Please let us know if the issue is persistent in the 1.8 releases.

**Closed by TehNut** 2016-01-17 20:10 UTC
Labels: question
