### ISSUE TITLE
1.16.3 Server side Lagg

### ISSUE THREAD

**Issue by ModernKnights** [WayofTime/BloodMagic#1708] opened 2020-11-10 12:59 UTC
#### Issue Description:
I tested bloodmagic on a server and i noticed my tps went down significantly yet there was no errors in the logs i used the alpha 1.16.3 3.0.0-3 version

#### Steps to reproduce:

1. download bloodmagic
2. run server
3. lagg happens
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.16.3-3.0.0-3
- Minecraft: 1.16.3
- Forge: 34.1.41

**Comment by WayofTime** [comment] 2020-11-10 13:26
Do you have a trace that shows which functions are using the most CPU?

**Comment by ModernKnights** [comment] 2020-11-10 13:28
i dont sadly idk how to get that , but all i did was just launching the server and after few mins of it being up tps goes down , i have 4 GB of ram dedicated to it , after i removed bloodmagic it seems stable

**Comment by WayofTime** [comment] 2020-11-10 13:30
It's unfortunately very hard to figure out what the issue is without a trace. I'll also ask some other people that are using the mod on a server.

**Comment by ModernKnights** [comment] 2020-11-10 13:31
ok , im really sorry i couldnt provide much , just thought id bring it to your attention <3

**Comment by ModernKnights** [comment] 2020-11-10 18:40
i ran spark sampler this is what i got (idk if it helps) https://spark.lucko.me/#4yPDHAdlWu

**Comment by lulabyte** [comment] 2020-11-12 15:11
Can confirm Blood Magic 1.16.3 3.0.0-1 is causing ticking on our server. But I see there's an update to Blood Magic since then and I'm going to try that.

**Comment by lulabyte** [comment] 2020-11-12 16:27
Latest Blood Magic update fixes ticking error for me.

**Comment by ModernKnights** [comment] 2020-11-12 16:31
> Latest Blood Magic update fixes ticking error for me.

i had issues with the 3.0.0-3 version , is that the one u using?

**Comment by lulabyte** [comment] 2020-11-12 16:33
Nah, sorry. I believe mine was the 3.0.0-1 version that was causing ticking errors on our server, especially after fast travelling around. It seems to be fixed upgrading to -3 but I'm going to have the players stress test.

**Comment by wrincewind** [comment] 2021-07-28 17:37
Given the lack of updates, i'm closing this as resolved.

**Closed as completed by wrincewind** 2021-07-28 17:37 UTC
Labels: bug, 1.16
