### ISSUE TITLE
Divination Sigil bug when reading Altar LP levels

### ISSUE THREAD

**Issue by Nikslg** [WayofTime/BloodMagic#957] opened 2016-10-21 10:26 UTC
#### Issue Description:

One Russian player of our private modpack was testing blood magic and encountered this.
![image](https://cloud.githubusercontent.com/assets/15956980/19595245/912e6998-9791-11e6-9392-7e3c9374897b.png)
#### What happens:

Two messages show up in the chat instead of the LP essence amount and capacity.
"tooltip.BloodMagic.sigil.divination.currentEssence"
"tooltip.BloodMagic.sigil.divination.currentAltarCapacity"
#### What you expected to happen:

Current Essences and altar Capacity to be shown.
#### Steps to reproduce:
1. Right click with divination sigil on altar.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: BloodMagic-1.9.4-2.1.0-65.jar
- Minecraft: 1.10.2
- Forge: 12.18.2.2107

**Comment by Arcaratus** [comment] 2016-10-22 18:40
Duplicate of #700 
Someone doing (or not doing) something wrong with the lang files again maybe?

**Closed as completed** 2016-10-22 20:11 UTC
