### ISSUE TITLE
Imperfect rituals seem bugged.

### ISSUE THREAD

**Issue by afghan2007** [WayofTime/BloodMagic#585] opened 2016-01-31 01:51 UTC
Ive been testing the imperfect rituals in creation mode.  I set them up with a water source/lapiz block/coal block on top of a imperfect ritual stone.  Activates stone of any variety do nothing when I switch to survival, but if I hit the imperfect ritual stone with my bare hand on a right click, I died.  Im at full health, I have 25000 LP and I die.  I see a message saying my soul is to weak or something like that.   Is this a bug.

**Comment by afghan2007** [comment] 2016-01-31 01:51
Ive never had this much trouble with regular rituals

**Comment by TehNut** [comment] 2016-01-31 02:03
Works as intended for me. http://gfycat.com/NeedyGentleIridescentshark 

Make sure you're on the latest version.

**Comment by afghan2007** [comment] 2016-01-31 02:06
im using 1.8.9-2.0.0-9.jar
Lapiz block on imperfect stone I cant get anything to happen, but the water source and coal kill me out right, i cant activate the ritual from far away but up close is certain death.

**Comment by afghan2007** [comment] 2016-01-31 02:13
"Your soul becomes to weak" is my epitaph.  The imperfect rituals are cosmetically cool, I just cant get them to work as the videos suggest, it may just be a bug in the 1.8.9-2.0.0-9.jar mod, but its frustrating.

**Comment by TehNut** [comment] 2016-01-31 02:21
Update to the latest version... Don't report bugs if you're outdated

**Comment by afghan2007** [comment] 2016-01-31 02:40
I thought this was the latest version, thats why i reported a bug.

**Comment by afghan2007** [comment] 2016-01-31 02:46
If 1.8.9-2.0.0-9.jar isnt the latest version of the blood magic mod then maybe you can tell me what is?  Im unable to locate a newer version.

**Comment by afghan2007** [comment] 2016-01-31 02:46
I see a bug report for the 10.jar but no download

**Comment by afghan2007** [comment] 2016-01-31 02:47
I wouldnt be reporting a bug if the ritual would actually work.

**Comment by TehNut** [comment] 2016-01-31 02:59
Go to CurseForge and download the latest version...

**Comment by TehNut** [comment] 2016-01-31 03:25
Well, I know that this is fixed in newer versions. If you update and the problem persists, come back here.

**Closed as completed by TehNut** 2016-01-31 03:25 UTC
Labels: invalid

**Comment by Blue64** [comment] 2016-01-31 04:02
- [**_`1.7`**_](http://minecraft.curseforge.com/projects/blood-magic/files?filter-game-version=1738749986%3A5)
- [**_`1.8`**_](http://minecraft.curseforge.com/projects/blood-magic/files?filter-game-version=1738749986%3A4)
