### ISSUE TITLE
Crash using the teleportation ritual

### ISSUE THREAD

**Issue by belathus** [WayofTime/BloodMagic#1123] opened 2017-04-10 06:50 UTC
#### Issue Description:
I think that there may be an incompatibilty between BlayThe9th's NetherPortalFix and BloodMagic's teleportation ritual.

#### What happens:
Someone on my server attempted to use a teleportation ritual.
Crash: https://pastebin.com/Rqjznwar

#### What you expected to happen:
Teleport from the moon (dimension -2) to the overworld.

#### Steps to reproduce:
1. @greenking13 might be able to give more detail than me here.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 2.1.9-78
- Minecraft: 1.10.2
- Forge: 12.18.3.2239

**Comment by greenking13** [comment] 2017-04-10 20:10
Apologies for not responding sooner, I wasn't aware that Belathus had added me to the crash discussion.

First off, the ritual was The Gate of the Fold, which requires a master ritual stone and 15 ritual stones (requiring a T4 Blood altar due to dusk runes.) per portal frame. From what I am aware of the ritual, each portal set has a calling id which can be created using the 40 adjacent blocks on the lowest level, (Distance of 2 blocks from the master ritual stone plus the other 4 ritual stones, making it so that a part of the ID is made from the 9x5x1 rectangle with the master ritual stone being the center.) as well the layer surrounding the exterior of the portal frame. (The 15 blocks that look to add a portal frame with size of 5 block width and 4 block height interior..)
Using this knowledge I created identical portals in both the overworld and Luna (The first moon that the mod Advanced Rocketry adds.) using the block moon turf to fulfill the positions of all the block locations stated above, except for a 3 block width and 2 block length (Following the same width definition stated above.) of Basalt bricks made from Chisel.
After getting the necessary amount of blood to activate both sides of the ritual, I traveled from the moon to the overworld, which promptly caused the server we are testing on, to crash.
After allowing the server to restart from crash, when I logged in, I was placed an estimate of 20 blocks above the location of the overwold portal and fell. (20 is a lousy estimate, it's just a rough number I made up taking into account that I fell from eye level of my base's roof and that the portal is underground about 10 blocks.) At this point in time I was asked not to attempt to gather any more information about the crash, or to recreate said crash until I was alone on the server.
When this occurred, I decided on the first course of action being that I should see what would happen if I tossed items into the portal. As far as I can tell, they were deleted upon touching the portal. My next attempt was to travel through the overwold portal, which ending with nothing happening. Same occurred when I attempted travel via the moon portal. From what I can gather, either the portals disabled themselves but left the red portal frame intact, or the portal id's were changed in transit and they no longer resembled each other.

That's the extent of my testing. Any mod versions can be requested from @belathus since I will be unable to acquire them until my exams are complete for the week.

Have a good day,
Greenking13

EDIT: Also, do note that when I am able to, and if you have not attempted so yourselves, I will build a small instance with just blood magic, nether portal fix, guide api, Advanced Rocketry, and LibVulpes (The library mod for Advanced Rocketry.) to test if the same issue occurs with just those mods enabled, then another pack without nether portal fix.

**Comment by greenking13** [comment] 2017-04-14 18:36
Update: So I attempted a single player version of the portal setup and produced the same crash as Belathus, when I included NetherPortalFix. But without NetherPortalFix, I still got a crash. (Different crash interestingly enough.) https://pastebin.com/Be8nkwBe

**Comment by TehNut** [comment] 2017-04-14 22:28
Dupe of #1104

**Closed as completed by TehNut** 2017-04-14 22:28 UTC
Labels: duplicate
