### ISSUE TITLE
Crashing when equipping final living armor piece

### ISSUE THREAD

**Issue by Moldyboss** [WayofTime/BloodMagic#1866] opened 2021-11-07 07:49 UTC
#### Issue Description:
Game crashes when equipping full living armor

#### What happens:
game crashes

#### What you expected to happen:
being able to equip living armor without crashing

#### Steps to reproduce:

1. equip all living armor
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.16.4-3.1.5-25
- Minecraft: 1.16.5
- Forge: 36.2.8
[crash-2021-11-07_01.31.04-client.txt](https://github.com/WayofTime/BloodMagic/files/7491900/crash-2021-11-07_01.31.04-client.txt)

**Comment by wrincewind** [comment] 2021-11-07 14:56
this is a duplicate of #1864 - the current fix is to downgrade to version 18 of blood magic, log in, unequip and delete the chestplate, update back to version 25, spawn in a chestplate from JEI (NOT via the /give command), and equip that. It'll be fixed in the next version.

**Closed as completed by wrincewind** 2021-11-07 14:56 UTC
Labels: bug, 1.16
