### ISSUE TITLE
[1.16.4] Tag was used before it was bound (ticking entity)

### ISSUE THREAD

**Issue by Gbergz** [WayofTime/BloodMagic#1748] opened 2021-01-12 10:54 UTC
#### Issue Description:
Someone from my discord reported this and describes it like this:
When I do a right click anywhere on a block ( chest, door ,furnace and other ) I crash and I have this error

#### What happens:
From Discord:
When I do a right click anywhere on a block ( chest, door ,furnace and other ) I crash and I have this error

#### What you expected to happen:
No crashes.

#### Steps to reproduce:
 Not exactly sure how to reproduce but, right clicking anything seems to have triggered it for him.

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 3.0.4-9
- Minecraft: 1.16.4
- Forge: 35.1.36

### Crash report
https://hatebin.com/qdqhjnmysq

### Additional info:
I reported this on the productive bees issue tracker thinking it was that mod, I was wrong something with the tags in bloodmagic?
More info here, JaisDK describes it better.
https://github.com/JDKDigital/productive-bees/issues/140

**Comment by WayofTime** [comment] 2021-01-13 16:56
Since this bug does not appear to be reproducable with the two mods listed, I am going to close this for now. If the crash happens again, please try to obtain the full log.

**Closed as completed by WayofTime** 2021-01-13 16:56 UTC
Labels: bug, compatibility, what?, cannot reproduce, 1.16
