### ISSUE TITLE
Teleposers crashing server when teleporting players between dimensions.

### ISSUE THREAD

**Issue by Agalyon** [WayofTime/BloodMagic#1127] opened 2017-04-14 22:08 UTC
#### Issue Description:
Teleposers crash the server when teleporting players between dimensions

#### What happens:
When attempting to use a teleposer to travel between dimensions (as a player,) the server closes without crashing clients, and upon reopening the player that attempted to teleport can be found a large distance away from the destination (usually at least 100 blocks) and often in walls.

As a note, I used the teleposers many, many times with no issues to travel between the deep dark and the overworld until today, and now it crashes every single time. It appears to only affect players. I even found a nether portal near where I was teleported at one point in the deep dark that I'm certain was not created by a player. This actually reminds me a lot of [#973](https://github.com/WayofTime/BloodMagic/issues/973) that I ran across while trying to solve this on my own.
#### Steps to reproduce:

1. Place two teleposers in different dimensions
2. Bind them and attempt to travel
3. Server crash
...
____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.10.2-2.1.9-78
- Minecraft: 1.10.2
- Forge: 2239
____
Crashlog: https://pastebin.com/0ZvEYUg6

**Comment by xenxero1** [comment] 2017-04-14 22:24
I thought teleposers weren't supposed to work x-dimensions

**Comment by Agalyon** [comment] 2017-04-14 22:26
I've never heard that myself. I've used them cross dimension in previous versions, and they were working fine on 1.10 for a while. They still seem to work just fine cross dimension for everything that isn't a player, at least what I tested at any rate.

**Comment by TehNut** [comment] 2017-04-14 22:29
Dupe of #1104

**Closed as completed by TehNut** 2017-04-14 22:29 UTC
Labels: duplicate
