### ISSUE TITLE
Mod Conflict breaks Snare - unable to collect first demonic will

### ISSUE THREAD

**Issue by JamesGrimm** [WayofTime/BloodMagic#745] opened 2016-05-17 18:24 UTC
#### What happens:

The "snare" item no longer works properly in my 1.9 custom modpack - it appears to effect me (the player) with the "soul snare" potion effect instead of the mobs. I tested against Zombies, Skeletons, and Spiders. This leaves me unable to collect demon wills to start the mod (noticed when I recently started a new 1.9 map, and had to start progression over again).

I tested in a clean build of just Minecraft, Forge 1907, and Blood Magic .38 - The snare works there just fine.

But one of the mods I have messing with potion effects is somehow shifting the effect to the player in my pack. I'm slowly trying to test which mod it is in the pack causing this, but I figured I should report it to your github since it completely stops entry into your mod and (being 1.9) my pack is relatively small.
#### What you expected to happen:

For the snare to put the potion effect on the mob I struck, so I could collect demon will from it, as it did in previous versions.
#### Steps to reproduce:
1. Create modpack on Curse client for 1.9
   Modlist:
   Random Things (by lumien231)
   HelpFixer (by matthewprenger)
   Ender Compass (by MrIbby)
   Fast Leaf Decay (by lumien231)
   Crafting Tweaks (by Blay09)
   Just Enough Resources (JER) (by Way2muchnoise)
   BetterAchievements (by Way2muchnoise)
   Compass Coordinates (by quetzi)
   Morpheus (by quetzi)
   MCMultiPart (by amadornes)
   Gentle Harvest (by BEQOsNtDi6xRDGzqIAT7)
   ElecCore | Rendering Library (by Elec332)
   Practical Anvil (by SViking)
   Iron Chests (by progwml6)
   Just Enough Items (JEI) (by mezz)
   McJtyLib (by McJty)
   RFTools (by McJty)
   Deep Resonance (by McJty)
   Waila (by ProfMobius)
   JourneyMap (by techbrew)
   Chisel (by tterrag1098)
   No Mob Spawning on Trees (by oldjunyi)
   airbreathercore (by AirBreather)
   YALSM - Yet Another Leather Smelting Mod (by AirBreather)
   Mantle (by mDiyo)
   Tinkers Construct (by mDiyo)
   Better Builder's Wands (by Portablejim)
   BetterBedrockGen (by Gigabit1011)
   Inventory Tweaks (by Kobata)
   Psi (by Vazkii)
   Quark (by Vazkii)
   Baubles (by azanor)
   Craftable Elytra (by mariofishy)
   Food Details (by Lothrazar)
   NetherPortalFix (by Blay09)
   Armor Recalc (by TheOldOne22)
   Refined Storage (by raoulvdberge)
   Chest Transporter (by CubeX2)
   Wawla - What Are We Looking At (by darkh4x)
   Baubles Stuff (by zazpro)
   Redstone Paste (by FyberOptic)
   Hopper Ducts (by FyberOptic)
   SimpleGraves (by TehNut)
   Bagginses (by lorddusk)
   Block Drops (JEI Addon) (by MrRiegel)
   Unity (by theCyanideX)
   MmmMmmMmmMmm (by bonusboni)
   RFTools Dimensions (by McJty)
   Blood Magic (by WayofTime)
   Enchanting Plus (by darkh4x)
   CodeChicken Core 1.8.9+ (by covers1624)
   ShadowMC (by shadowfactsmc)
   Sleeping Bag (by shadowfactsmc)
   Biomes O' Plenty (by Glitchfiend)
   Roguelike Dungeons (by Greymerk)
   Ender Crop (by DrMathiasDJ)
   More Overlays (by feldim2425)
   Pam's HarvestCraft (by MatrexsVigil)
   EZStorage (by zero__fall)
   Flux Ducts (by FyberOptic)
   Base Metals (by Cyanobacterium)
   Nether Metals (Base Metals Addon) (by koxhack)
   Bookshelf (by darkh4x)
   Botania Unofficial (by williewillus)
   Chisels & Bits (by AlgorithmX2)
   Chunk Animator (by lumien231)
   BetterFps (by Guichaguri)
   Ender Storage 1.8.9+ (by covers1624)

All of the above are the most recent version available through Curse Client as of 5/17/2016.
1.  Make a snare. Make a stack.
2. Throw at mobs - note potion particles never appear on the mob from the snare
3. Notice white particle effects around the player - Player is effected by soul snare.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 38
- Minecraft: 1.9
- Forge: 1907 (and 1906)

**Comment by TehNut** [comment] 2016-05-17 19:35
Could you try the sentient bow in both instances to test for #744 please?

**Comment by benedict42** [comment] 2016-05-19 05:43
Ya, I have this problem too. I can at least say my mod pack is a bit less populated and a bit different. I think I blame RF tools. It started about when I added it.

Out of the mods JamesGrimm has, I have (by name):

Biomes O' Plenty (by Glitchfiend)
Blood Magic (by WayofTime)
JourneyMap (by techbrew)
Just Enough Items (JEI) (by mezz)
Mantle (by mDiyo)
McJtyLib (by McJty)
Pam's HarvestCraft (by MatrexsVigil)
Psi (by Vazkii)
RFTools (by McJty)Wawla - What Are We Looking At (by darkh4x)
Tinkers Construct (by mDiyo)
Waila (by ProfMobius)

**Comment by TehNut** [comment] 2016-05-19 05:56
So just to be clear, the problem goes away when RFTools is removed?

**Comment by benedict42** [comment] 2016-05-19 23:07
Kinda.
I just tested removing RFtools and McJtyLib and it worked perfectly. I then added back McJtyLib and it wasn't impossible, but it was hard to get a Will. I then added RFtools back, and again, getting a Will was still hard.

I now blame McJtyLib. I don't know how, but it is the one that messed with the snares.
Interesting behavior to note: spamming the snares seems to help your chances?

Edit: The mod version/file I have is 'mcjtylib-1.9.0-1.8.4'.

**Comment by WayofTime** [comment] 2016-06-17 14:20
Is this still an issue?

**Comment by JamesGrimm** [comment] 2016-06-17 23:21
I'm on 1.9.4 now and it does not seem to be, I was able to get will to start the progression on a test pack, both your mods and McJtys have had a few updates since then.

**Comment by kayila** [comment] 2016-07-10 21:54
I am also seeing this problem with minecraft 1.10, and I also have RFTools and McJtlLib

Minecraft Forge: 1.10.2-12.18.0.2008
Blood Magic: 1.9.4-2.0.2-50
RFTools: 1.10-5.03
RFTools Dimensions: 1.10-4.30beta45
mcjtylib: 1.10-1.9.6

**Comment by Arcaratus** [comment] 2016-11-11 15:26
This issue (if it still is) should be reported to McJty (if it hasn't already) or should be closed.

**Comment by WayofTime** [comment] 2016-11-11 15:29
Closing due to no recent updates.

**Comment by kayila** [comment] 2016-11-11 15:29
Yes, I am still seeing this bug

**Comment by WayofTime** [comment] 2016-11-11 15:31
Do you have the most up-to-date versions of the mods?

**Comment by Arcaratus** [comment] 2016-11-11 15:34
The EntitySoulSnare should be blacklisting impact with the player anyways. https://github.com/WayofTime/BloodMagic/blob/1.9/src/main/java/WayofTime/bloodmagic/entity/projectile/EntitySoulSnare.java#L33

**Comment by kayila** [comment] 2016-11-11 15:34
To be clear, killing a mob with any sentient weapon does drop the appropriate will, it's just the soul snare that doesn't work. The way I've been working around this is by spawning in a gem and sword, killing 2-3 zombies, then deleting the spawned items and continuing as per normal.  I'll check when I get home to see if it's still the case, but it was still this way a few weeks ago when I started BloodMagic in the new world with my pack.  Current versions of BloodMagic and MyJty stuff is:

```
BloodMagic-1.9.4-2.1.0-65.jar
mcjtylib-1.10-2.1.4.jar
rftools-1.10-5.51.jar
rftoolsdim-1.10-4.41.jar
rftoolsctrl-1.10-1.2.0.jar
```

Minecraft: `1.10.2`
Forge: `1.10.2-12.18.2.2123`

**Comment by kayila** [comment] 2016-11-11 17:37
Confirmed that the bug still does exist in the version I stated above.

**Closed as completed** 2017-02-13 01:03 UTC
Labels: bug, Fixed in Dev, compatibility, 1.9, 1.10
