### ISSUE TITLE
java.lang.NoSuchFieldError: blockForOverlay

### ISSUE THREAD

**Issue by Dhs92** [WayofTime/BloodMagic#469] opened 2015-10-13 03:14 UTC
http://pastebin.com/EiyC7ZZh
http://prntscr.com/8qp1u1

**Comment by TehNut** [comment] 2015-10-13 06:05
You're using 1.8 which isn't supported in the slightest. Remove it.

**Comment by TehNut** [comment] 2015-10-13 06:17
Also a dupe of #443

**Comment by WayofTime** [comment] 2015-10-13 11:27
Yeah, we haven't done much of any work on 1.8. Sorry!

**Closed by WayofTime** 2015-10-13 11:27 UTC

**Comment by Dhs92** [comment] 2015-10-13 14:07
Heh, last time I use Curse for mods ;p

**Comment by TehNut** [comment] 2015-10-13 17:12
I don't see what Curse has to do with this?
