### ISSUE TITLE
[1.16.5] Null Pointer Ticking Entity (hard crash) when Creeper explodes nearby

### ISSUE THREAD

**Issue by Seth0067** [WayofTime/BloodMagic#1808] opened 2021-04-06 22:49 UTC
#### Issue Description:
In a custom pack on Curseforge, whenever a Creeper tries to explode, the game hard crashes with the crash logs below. Happens in the blood magic itil.handler? So I thought to see if you could use these. :)

#### What happens:
In the few instances this has happened, Creepers have come up behind me and I hear the fuse sfx trigger. Once that plays, the game goes down. HARD. 

https://pastebin.com/VD3arxUM
https://pastebin.com/dRC96jfM

#### What you expected to happen:
Explosion, tears, etc.

#### Steps to reproduce:

1. You can use this instance at (https://www.dropbox.com/s/eqyh19i8nl9m3rn/Test%20Instance%20Forge%2036.1.2.zip?dl=0)
2. Load up the World save and wait until you see some creepers spawn nearby (grove of dark oak trees usually). 
3. Pretend you don't see them and pretend to do gardening nearby.
4. Wait for fuse sfx as you are rudely interrupted.

...

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic-1.16.4-3.1.0-15.jar
- Minecraft: 1.16.5
- Forge: 36.1.2 and 36.1.4 (I updated Forge on an instance named after the version number. Yeah, I know)

**Comment by Seth0067** [comment] 2021-04-07 06:14
Also, since I use Optifine, I did replicate the crash without that mod.  Pastebin for that crash: [Pastebin Link](https://pastebin.com/8vMRRuZb)

**Comment by TochaFh** [comment] 2021-04-07 15:18
I reproduced the same error (I think) in my modpack, but with an item from [MowziesMobs](https://github.com/BobMowzie/MowziesMobs) mod... I submitted an issue there: https://github.com/BobMowzie/MowziesMobs/issues/391.

Obs: The version of bloodmagic is different, the creepers don't cause the bug in my modpack.

**Comment by TochaFh** [comment] 2021-04-07 15:32
I updated bloodmagic to the latest 1.16.5 version and now everything is working!

**Comment by Seth0067** [comment] 2021-04-07 17:05
@WayofTime to be clear the two above comments have nothing to do with this bug (as someone who has limited time I would possibly see the above comment and assume all's good)

**Comment by neboy421** [comment] 2021-04-11 19:55
a similar issue that is reproducable. from what it looks like to me is an overlapping loot drop/check looting between these 2 mods.

reproducing:
with these 2 mods let creeper explode to cause the crash.

Crash report:
https://pastebin.com/2PvGHzUY

•BloodMagic-1.16.4-3.1.0-15.jar
•ScalingHealth-1.16.5-4.0.5+5.jar
•forge-36.1.4

**Comment by wrincewind** [comment] 2021-07-28 16:58
Looks like this has been fixed, so i'm going to close it for now.

**Closed as completed by wrincewind** 2021-07-28 16:58 UTC
Labels: bug, 1.16
