### ISSUE TITLE
Teleposers don't work in SMP when owner is offline

### ISSUE THREAD

**Issue by arketec** [WayofTime/BloodMagic#1411] opened 2018-08-22 20:42 UTC
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:
Teleposers do not work on SMP unless the owner of the teleposer is online. Even if LP is stored in that players network, in loaded chunks

#### What you expected to happen:
I expected teleposers to not require the owner's online presence. Makes them hard to use as entrances 
on SMP worlds

#### Steps to reproduce:

1. Owner places teleposers and links them
2. Owner logs offline
3. Second player attempts to use, but it does not work
4. Owner logs back onto server, second play can use teleposers now

____
#### Affected Versions (Do *not* use "latest"):

- BloodMagic: 1.12.2-2.2.12-97
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

**Comment by LemADEC** [comment] 2018-08-25 13:49
DUP of #1407

**Comment by TehNut** [comment] 2018-08-26 20:00
Duplicate of #1407

**Closed as completed by TehNut** 2018-08-26 20:00 UTC
Labels: duplicate
