### ISSUE TITLE
Crash when obtaining WillChunk

### ISSUE THREAD

**Issue by TehNut** [WayofTime/BloodMagic#667] opened 2016-03-14 19:06 UTC
#### Issue Description:

NPE when obtaining current will from the Chunk.
http://paste.ubuntu.com/15386157/

Reported [on CurseForge](http://minecraft.curseforge.com/projects/blood-magic?comment=102):

> So, I made the Demon Pylon and attached it to the side of an empty HellFire Forge a few days ago. I acquired my Greater Tartaric Gem and was out at night slaying massive amounts with my 9.5 Sentient sword and awesomely upgraded living armor when suddenly :O
> [Snipped crashlog]
> Was pretty close to filling that greater gem if that matters. Sadly I can't get back into my world without getting this beast ^-^

I'm not sure how to reproduce, but it looks like the problem code is that there's no null-checks after calling [`getWillChunk(int, int, int)`](https://github.com/WayofTime/BloodMagic/blob/1.8/src/main/java/WayofTime/bloodmagic/demonAura/WorldDemonWillHandler.java#L24) which can return null.

Just leaving the issue because I'm not sure how this system works and I'd rather you touch it. Also because I'll probably forget to tell you :D

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 2.0.0-19
- Minecraft: 1.8.9
- Forge: 11.15.1.1764

**Comment by WayofTime** [comment] 2016-03-14 19:09
Thanks, Nut. The issue is that WillChunks are populated on chunk load, not chunk creation. So a very fresh world would have this issue if you don't log off and log back in. I'll code in the proper way to do it later tonight/tomorrow.

Edit: Why the heck did I say "Nick"?

**Comment by painter73** [comment] 2016-03-15 01:26
This is not a new world though. I have been playing with your mod for 3 weeks or better now(at least 3 /hrs day. I just happen to make the Demon Pylon just because I could, hooked it to an empty HellFire forge, only because everything else seem to work off it. I really have no idea what it does or is suppose to do. But I did that at least 3 days ago irl(20MC days). I had the greater tartaric gem just about filled and it might of filled and the pylon took over.?. And BOOM goes the dynamite!! I was only 3-4 chunks away from my home to fill my will.

**Comment by TehNut** [comment] 2016-03-15 01:48
It would still occur with new chunks, though. Also, this was fixed in 22bd2f0628101e50dc03b0b51fca905b18fb4748.

**Comment by painter73** [comment] 2016-03-15 02:08
obviously it wasn't fixed..my house is totally visible (within 8 chunks) and I was only 4 chunks away (tops) and been playing this world for weeks. I have visited these chunks from day 1, there is nothing new. Only that my greater tartaric gem filled up and that pylon took over, that's when i crashed.(3-4 chunks away...but nothing 'new' or I haven't been hundreds of time before.

**Comment by WayofTime** [comment] 2016-03-15 02:09
When he says "this was fixed in blah" he means it was just fixed today.

**Comment by TehNut** [comment] 2016-03-15 02:12
This fix won't be in a release until the issue is closed. The `code-complete` tag means that the source has the fix in it.

**Comment by painter73** [comment] 2016-03-15 02:42
Thank You guys!! For all your hard work :D

**Closed as completed** 2016-03-17 20:29 UTC
Labels: bug, Fixed in Dev, 1.8
