### ISSUE TITLE
[1.9]Enhanced knife does activate properly

### ISSUE THREAD

**Issue by creodor** [WayofTime/BloodMagic#786] opened 2016-06-07 00:31 UTC
#### Issue Description:

When I have an incense fueled enhancement to my knife, the knife becomes unusable. Instead of cutting me on right click, it attempts to draw back like a bow.
#### What happens:

Instead of cutting and getting LP into the altar, the knife shows the draw back/bow animation and does nothing 9 times of 10. On occasion, it will seem to cut, take me to 1 heart, but not add anything to the altar and my health will not regenerate until I disconnect and rejoin the server. Even more rarely, the knife will actually successfully cut and provide LP, allow me to heal, and then de-enhance.

The only way I've found to de-enhance the knife if I'm unable to get it to successfully cut me is to delete my character file from the server and rejoin. This is what I typically have to do if I make the mistake of getting near an altar.
#### What you expected to happen:

The enhanced knife should instead cut me, take 9 of 10 hearts, provide boosted LP to the altar, allow me to heal, and provide soul fray for 20 seconds.
#### Steps to reproduce:

I am not 100% certain but I suspect that it was due to my placing an altar, enhancing my knife, not using it, and then another server player breaking and moving/upgrading the altar. All of this happened in the Nether, if that matters. As such:
1. Place incense altar
2. Walk near to activate the enhancement/bonus
3. Log off
4. Access with another character
5. Break the incense altar
6. Move and upgrade the altar
7. Log back on with the original character
8. Attempt to use the knife

I realize this may not be easy or even possible to duplicate, since I'm still not sure if this is actually what caused it to happen. I can provide any additional files or information you need.

---
#### Affected Versions (Do _not_ use "latest"):
- BloodMagic: 1.9-2.0.0-38
- Minecraft: 1.9
- Forge: 12.16.1.1907

**Comment by ZiggyAdventures** [comment] 2016-06-07 00:56
I've had the same issue on a server. I have a easier work-a-round. Instead of deleting your character, get damaged, use a blood orb or anything. It will reset your life/hunger to as if you never cut yourself. Then you can correctly cut yourself and get the knife De-enchanted. Haven't figured out how to deal with the Soul Fray effect lasting at 0 sec forever due to it, but at least that happens rarely.

Edit:
This is on a 1.9.4 server for All the Mods Modpack
Blood Magic: 1.9.4-2.0.1-42.jar
Forge: 12.17.0.1954

**Comment by creodor** [comment] 2016-06-07 12:25
Just checked on my server, thank you for that workaround. Simply getting hurt is a large improvement over having to delete my character! I have noticed the 0 second Soul Fray as well, but had forgotten due to its rarity. Thanks for mentioning that.

**Comment by WayofTime** [comment] 2016-06-07 14:01
Do you just tap the knife, or pull it all the way back?

**Comment by ZiggyAdventures** [comment] 2016-06-07 14:09
Once it gets bugged, tapping does starts pulling animation, holding continues pulling animation. On a side note(I haven't fully tested it yet), it almost seems as it happens when the enhanced cutting would put more blood in the Altar then it had hold, causing some kind of desync between client and server. Upon further testing, the 0 second Soul Fray looks to be a client side visual glitch from the bug above. Once unglitched, wait 20 seconds before using the knife to make it disappear. Using the knife after damaging oneself will restart the invisible 20 seconds saying 0 seconds in inventory. Feel free to task me with additional testing. I'll continue watching but the server I play on is down temporary.

**Comment by WayofTime** [comment] 2016-06-07 14:25
Might be because you still have Soul Fray, since it prevents sacrificing entirely with the enchanted knife. Does this only occur when Soul Fray is stuck at 0s?

**Comment by ZiggyAdventures** [comment] 2016-06-07 14:41
Now I can't get it to trigger lol, The soul fray gets stuck at 0 ONLY after the initial bug happens, never without.

**Comment by WayofTime** [comment] 2016-06-07 14:42
Will milk clear the debuff? That should help in the interim.

**Comment by ZiggyAdventures** [comment] 2016-06-07 14:43
The soul fray can be fixed by waiting after getting damaged, I was just mentioning to give you more info. The first bug seems to be more serious.

**Comment by WayofTime** [comment] 2016-06-07 14:49
Yes I figured it was a more serious issue. That is why I am trying to troubleshoot with you. One of the reasons that may make it not work is if you had soul fray stuck on. Therefore I wanted to see if it only happened when you had the debuff on, and not before.

**Comment by ZiggyAdventures** [comment] 2016-06-07 15:01
Give me some time, I haven't figured out how to trigger it, I'll get back to you in an hour.

**Comment by ZiggyAdventures** [comment] 2016-06-07 15:30
Okay, so both of us were impatient for the Soul Fray. Still working on why it's caused. The glitch happens where life goes down, no blood goes in altar, and soul fray gets applied for 20 seconds. Getting damaged does reset your life to before. But while Soul Fray is active, and using the knife before the 20 seconds, resets the time for the buff without reseting the time shown on inventory. So when it counts to 0 it stays at 0 till 20 seconds of time since Last knife use happened. The knife remains enchanted, and can be used after that 20 seconds after last knife use happens along with Soul Fray debuff going away(This is also not always the case and sometimes it remains at 0 duration past 20 seconds of nothing and you CAN use the sacrifice dagger, I'm so confused). Also, the bucket of Milk crashed me(But it works in my single player test world with just Blood Magic so ignoring for now). Here's a quick video if you'd like to see it in work, notice the blood spike up and down when it happens. https://www.youtube.com/watch?v=TPIG0nqjokE

I believe I debunked my own theory on the full Altar. In the video it appears to happen right as Soul Fray disappears. However fuhrer testing using the knife while soul frayed before the bug around and outside the Altar or right at Soul Fray end made it trigger once out of multiple times. I've also had it happen on first cut. I'll get back to you as soon as I find a way to duplicate that.

**Comment by WayofTime** [comment] 2016-06-07 16:15
So the knife will apply soul fray even if no health is sacrificed? I can fix that easily, I think...

**Comment by ZiggyAdventures** [comment] 2016-06-07 16:16
I'm refraining from putting more down for now. Every time I think I'm onto something I disprove myself :(

**Comment by WayofTime** [comment] 2016-06-07 16:16
Welcome to the world of bug fixing!

**Comment by Xiaminou** [comment] 2016-06-09 13:44
There appears to be a desync between client and server, the knife doesn't go back to "default" on the client after being used. Which is why you have to go back to the Altar.
Here is my video of it: https://youtu.be/40Wo8TEK2y0

**Comment by TehNut** [comment] 2016-08-14 20:54
Does this still happen?

**Comment by WayofTime** [comment] 2016-08-27 00:32
Since we haven't gotten anyone to reproduce this lately, I will close this for now. If anyone experiences this again, let me know.

**Closed as completed by WayofTime** 2016-08-27 00:32 UTC
