### ISSUE TITLE
imbued slate blood altar issue

### ISSUE THREAD

**Issue by bigfrogs** [WayofTime/BloodMagic#1232] opened 2018-02-18 19:14 UTC
#### Steps to reproduce:

1. get tier 3 altar, reinforced slate, and seer's sigil
2. place reinforced slate in blood altar with the required 5000 lp
3. observe recipe progress with seer's sigil
...

____
#### Affected Versions (Do *not* use "latest"): 

- BloodMagic: BloodMagic-1.12.2-2.2.5-88
- Minecraft: 1.12.2
- Forge: 14.23.2.2611

**Comment by TechnoMysterio** [comment] 2018-02-18 22:00
Can confirm this issue, trying to turn a Reinforced Slate into an Imbued Slate using a Tier III altar results in the Reinforced Slate stopping at 2000mb of blood instead of 5000mb and failing to turn into an Imbued Slate, before it tries to do it again shortly afterwards.

**Comment by TehNut** [comment] 2018-02-18 22:11
I'm not able to reproduce this. It properly runs all the way from Stone to Ethereal Slates.

**Comment by TechnoMysterio** [comment] 2018-02-18 22:16
Hmm, odd. I've also tested it further with higher-tier slates, and they turn into Reinforced Slates at 2000mb of blood. Could this be to do the altar reading metadata wrong?

**Comment by TehNut** [comment] 2018-02-18 22:24
Try with https://waifu.me/file/BloodMagic-1.12.2-2.2.5-CUSTOM.jar

**Comment by TechnoMysterio** [comment] 2018-02-18 22:36
That seems to work properly, even at the highest tiers. Also, are you working on the inscription tools by any chance? Just wondering because they seem to be missing textures and localisations in that custom build.

**Comment by TehNut** [comment] 2018-02-18 22:36
I extended the wrong class 👍

**Comment by TehNut** [comment] 2018-02-18 23:56
This is fixed by ee42f6ddc25037c776193532956b54901e904cfd for the record

**Closed as completed** 2018-02-19 00:24 UTC
Labels: bug, Fixed in Dev, 1.12
